all:
  children:
    backup:
      hosts:
        backup.nu.education:
          hostname: backup.nu.education
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          # person`s email responsible for this server
          mailto: boris.szelcsanyi@cleoag.ch